### ISSUE TITLE
Make it available via browser

### ISSUE THREAD

**Issue by suoko** [strukturart/o.map#13]
You could make the app available via browser and githubpages, I remember I did it with https://suoko.github.io/mapboxnav

**Comment by jm42** [comment]
Like a PWA manifest you mean?

**Comment by strukturart** [comment]
yes, the app is already running as a PWA (maybe it's leaning too far out of the window) but i don't know how to transfer the data between the app on the phone and the app on the desktop browser. first i tried a qr code, but the camera on the phone is too bad to read so much data.

**Comment by suoko** [comment]
@strukturart  can I use your app using Firefox on android just following a link?

**Comment by strukturart** [comment]
no, because the app is not yet online on any server. you are welcome to do it. however, the app has no special features except that it runs on kaiOs.

**Comment by suoko** [comment]
I always wanted to do something like this https://github.com/ffwdme/ffwdme.js/blob/master/README.md
That would be nice for kaios

**Comment by strukturart** [comment]
https://strukturart.github.io/o.map/
