### ISSUE TITLE
Start with last known postition

### ISSUE THREAD

**Issue by sibeliusg** [strukturart/o.map#21]
I have a feature request. Some devices have a weak GPS and rather slow GPS-fixes. By default o.map starts in Togo, if the position is not found after a certain time. It would be much nicer, when it would start with the last known position. Thanks!

**Comment by strukturart** [comment]
how about defining a homebase marker in the settings, if the position is not found when starting the app, is the homebase marker set?

**Comment by sibeliusg** [comment]
How to do that? I can't find such a setting

**Comment by strukturart** [comment]
it is not yet built into the settings, but I have tried to implement your idea of the last known position, please try it out: https://github.com/strukturart/o.map/tree/unknow-position

**Comment by sibeliusg** [comment]
Awesome! That's what I was looking for!
