### ISSUE TITLE
Share way point

### ISSUE THREAD

**Issue by Mikeruss** [strukturart/o.map#23]
When sharing waypoint through SMS it seams that longitude and latitude are crossed in the sms link.

**Comment by strukturart** [comment]
please try this version: https://github.com/strukturart/o.map/blob/master/build/omap.zip

**Comment by strukturart** [comment]
please try this version: https://github.com/strukturart/o.map/blob/master/build/omap.zip

**Comment by Mikeruss** [comment]
Now it works fine! Thank you a lot!

**Comment by strukturart** [comment]
how do you install the app ?

**Comment by Mikeruss** [comment]
I'm using ADB and Pale moon as described here: file:///C:/Users/Mikhail/Documents/KaiOS/Side-loading%20and%20deploying%20custom%20apps%20to%20KaiOS%20-%20Martin%20Kaptein.html

UPD to this task: coordinates were not crossed, they were zeros. This also happen if GPS were not assigned satellites. Maybe when sharing location to make some warning, that coordinates are blank and user needs to wait some time.
