### ISSUE TITLE
build is in fact broken

### ISSUE THREAD

**Issue by Unixware** [strukturart/o.map#30]
can't install, error: "MissingMetadataFile"

**Comment by strukturart** [comment]
can you sideload the app ?

**Comment by Unixware** [comment]
yeap, it's just needs the extra metadata files using the OmniSD, as 3rdparty store apps are dead meats

**Comment by strukturart** [comment]
file: https://github.com/strukturart/o.map/releases/tag/1.3

do you know these ?
https://store.bananahackers.net/#
https://gitlab.com/affenull2345/store-client

**Comment by Unixware** [comment]
oh mate! that's wonderful! I only knew the 2 stores (one from  your repos bHacker-store-client ) and the OpenGiraffes that stopped working since a month!  MANY THANKS for the link!!!
