### ISSUE TITLE
keypad becomes unresponsive on home screen when press right arrow

### ISSUE THREAD

**Issue by erdosnew** [strukturart/o.map#32]
hi,  I've experiencing issue with o.map on a ATT's Cingular Flip IV phone.

I installed the apps onto my phone and recently updated to ver1.4.3.  it seems that right arrow key on keypad was remapped to bring up option 'o.map', along with default 'system',  often when i pressed right arrow, keypad becomes unresponsive, with only 'message' key  works.   I had to long pressed 'power' button to restart the phone to restore the keypad functions.  

The right arrow was linked to att homepage before the installation of o.map.  after i removed the o.map, right arrow launches att homepage and keypad functions normally.

**Comment by strukturart** [comment]
I don't quite understand the issue, you're talking about the o.map having an effect on the key mapping of the system?

**Comment by erdosnew** [comment]
the right arrow button on the Flip IV's keypad is hardwired to open att's homepage https://home.att.com/,  with o.map installed, pressing the same button results an option screen 'view with...  System or o.map'.   

in my case, when i pressed right arrow on the keypad, the phone sometimes becomes unresponsive with any keypad inputs, with the exception of 2nd row's 'text message' button.   I have a shortcut located on the menu which pointed to 'duckduckgo' search page, by selecting this app icon, it also what to know whether i want to open 'o.map' or 'duckduckgo'.

Hope this clarify the issue.

**Comment by erdosnew** [comment]
wow, fast response!

I installed the apps through appstore when i first noticed the issue, i think it starts with 1.4.3 update recently.

yesterday i sideloaded the app with adb tools and palemoon's WebIDE (thanks for the detailed instruction on the this page),  so far the issue hasn't repeated itself, however the mapping of arrow key still open the option screen 'view with... 1 system 2 o.map'.  the pinned 'duckduckgo' app in menu screen also wants to know view with system or o.map.

**Comment by strukturart** [comment]
please try the latest version, the bug should be fixed.
https://github.com/strukturart/o.map/releases/tag/1.4

**Comment by erdosnew** [comment]
thanks!  tried the latest and right arrow button no longer maps to o.map and it launches web browser by default.

Issue is resolved!

**Comment by strukturart** [comment]
pls checkout the new version, I made some improvements. you might also be interested in using your own layers: https://github.com/strukturart/o.map#custom-maps-and-layer
