### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by danieldegroot2** [strukturart/o.map#38]
Hey John,

I noticed the following;
- The app has no copyright and license links
- The desktop version has no attribution at all

Make sure you have proper attribution for all map layers;
For copyright, see https://www.openstreetmap.org/copyright for OpenStreetMap for example.
For license, see ex. CreativeCommons website. You can also use https://chooser-beta.creativecommons.org/ to get some basic text (to display elsewhere).

**Comment by strukturart** [comment]
the dumbphone for which the app is intended only has keys, which is why the browser version is only key only. with enter you get to the menue for the layers switch etc. attribution now stays visible at > 600px viewport.

**Comment by danieldegroot2** [comment]
Minor suggestions:
- The weather layer doesn't show any additional attribution when toggled on. [example](https://www.meteopool.org/de/livemap) (unfortunately attribution for [DWD](http://www.dwd.de/) is partially hidden by advertisement; there's also bottom advertisement which you can collapse)
- It would be nice to show the copyright links for OpenTopoMap, OpenStreetMap and possibly Esri itself (at least on Desktop, as you always see them there). All others are fine without one generally.
- There's two copyright icons in the first part of the OpenTopoMap attribution.
- On satellite, the long attribution text is for a fraction hidden by the menu icon. You could try to position the attribution just above the menu icon, so the UI remains consistent.

Other minor suggestions:
- The menu should remember/highlight which layer you have selected, Currently, when OpenStreetMap (default) or Satellite is selected OpenTopoMap is always highlighted on opening the menu because it is at the top.
- The weather layer is a toggle. maybe there should be a visual indicator to show whether you have it toggled on or off.
- The weather layer flickers every second or so. Is this to update it? If so, it may be better to only update every five minutes (or with a refresh button/key).
- The menu icon at some point changed to a white square for me, so the image must have failed to load. I could try to reproduce it, but it's very minor as on reload it loads again.

**Comment by LolloDev5123** [comment]
Will the attribution fit on a 240x320 screen?

**Comment by danieldegroot2** [comment]
> Will the attribution fit on a 240x320 screen?

It would fit, though
- they may need/have a different display method than leaflet's attribution container for this size.
- as mentioned, they may ask LWG what display options are prefered.

When you search your prefered browser you should find something like this btw (these examples may no longer be available);
![image](https://user-images.githubusercontent.com/67521919/161279344-a68dd1ba-c68d-45c3-88f8-03ddf8b6e6a3.png)
('xMaps')

![image](https://user-images.githubusercontent.com/67521919/161279975-ca45eb40-15ad-48e3-87b6-9592122ab057.png)
('Hyves')

(note, especially when shown on the map itself, low contrast with background makes it less visible; with modern software it's easier to adjust this to now existing -optional- accessibility standards (a.o. WCAG), which require sufficient contrast for those with less eyesight. These optional standards are usually considered a very low priority issue.)

**Comment by danieldegroot2** [comment]
---
Feel free to [look at good attribution examples](https://wiki.openstreetmap.org/wiki/They_are_using_OpenStreetMap) for inspiration (not saying they are perfect).

**Comment by strukturart** [comment]
I have now added the attributions and added links to the sources in the menu. the desktop is only a showcase for the kaiOs users to show the functionality of the app. there are far better websites such as: umap which i use myself to plan tracks. I realize that I was a bit lax about specifying the data sources, but I think it should be ok now. please install the app on a kaiOs device then you will see how tight the space on the device is and you have to make some compromises.
