### ISSUE TITLE
openstreetmaps and opentopomaps not loading on device and simulator in 1.9.2

### ISSUE THREAD

**Issue by juhench** [strukturart/o.map#49]
Hi! I have noticed that this fantastic app (thanks a lot!) no longer loads the openstreetmap and opentopomap tiles both in the KaiOS simulator and physical devices. The only tiles that work are those from the satellite map. I have tried two devices: Nokia 8000 4G and E242s. Could it be that the URLs have changed? Strangely enough, I can load the tiles already cached on the installed older version 1.8.0. is it possible that the URL has changed for those two map sources? Kind regards, JH.

**Comment by strukturart** [comment]
when I make a request, I get a 418 status, which unfortunately means that the app was blocked -> https://www.paulnorman.ca/blog/2021/07/standard-layer-2/

**Comment by strukturart** [comment]
As an alternative, I have put together a few layers for you that work. create a file: omap_maps.json and copy the content into it and then copy the file to your sdcard of your phone. The next time you load you will have new cards to choose from in the menu. for the trace map you have to add an api key in the url, you can get the key here https://console.tracestrack.com/




**omap_maps.json**

```
[
  {
    "name": "Hiking",
    "type": "overlayer",
    "url": "http://tile.waymarkedtrails.org/hiking/{z}/{x}/{y}.png",
    "attribution": "hiking.waymarkedtrails.org",
    "maxzoom": 18
  },

  {
    "name": "Google Satelite",
    "type": "map",
    "url": "http://mt0.google.com/vt/lyrs=r&hl=en&x={x}&y={y}&z={z}",
    "attribution": "Google",
    "maxzoom": 18
  },
  
  {
    "name": "trace",
    "type": "map",
    "url": "https://tile.tracestrack.com/topo__/{z}/{x}/{y}.png?key=1234",
    "attribution": "tracestack",
    "maxzoom": 18
  },
  
 
 
  {
    "name": "Google Hybrid",
    "type": "map",
    "url": "http://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
    "attribution": "google.com",
    "maxzoom": 18
  },

{
    "name": "Cycling",
    "type": "overlayer",
    "url": "https://tile.waymarkedtrails.org/cycling/{z}/{x}/{y}.png",
    "attribution": "waymarkedtrails.org",
    "maxzoom": 18
  },

  {
    "name": "climbing",
    "type": "overpass",
    "url": "sport=climbing",
    "attribution": "Overpass",
    "maxzoom": 18
  },

  {
    "name": "water",
    "type": "overpass",
    "url": "amenity=drinking_water",
    "attribution": "Overpass",
    "maxzoom": 18
  }
]
```

**Comment by juhench** [comment]
Thank you so much for this! I was just about to try creating something like this. I will report back a.s.a.p. Fantastic piece of software.

**Comment by juhench** [comment]
It works! Thank you so much! I did not even need to move the file from the downloads directory. Confirmed to work on the E242S.

**Comment by juhench** [comment]
I am closing this issue now.

**Comment by juhench** [comment]
Closing this issue.

**Comment by strukturart** [comment]
looks like opentopomap is working again.
