### ISSUE TITLE
1.9.744 no search or download on KaiOS 2.5.2.2 (Nokia 800 Tough)

### ISSUE THREAD

**Issue by fustygerbil** [strukturart/o.map#51]
Search [2] and download [#] shortcuts do nothing since update to 1.9.744 on KaiOS 2.5.2.2 on Nokia 800 Tough. These worked under the previous version of o.map about a week ago before the update.

p.s. thank you for this outstanding app and its continued development and expansion.

**Comment by strukturart** [comment]
@fustygerbil thanks for reporting!

I can fix the bugs, if you would like to send me your IMEI to structurart@gmail.com then I can add you as a tester in the store so you will receive the latest version of the app.
